# Generated by Django 2.0.4 on 2018-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location_address',
            field=models.TextField(blank=True, help_text='Address of the location'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location_name',
            field=models.TextField(blank=True, help_text='Name of the location'),
        ),
    ]
