# Generated by Django 2.0.4 on 2018-04-20 21:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180420_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='eventpageevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventpageevent',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_events', to='events.EventPage'),
        ),
    ]
