# Generated by Django 2.0.4 on 2018-04-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180420_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpageevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpageevent',
            name='page',
        ),
        migrations.DeleteModel(
            name='EventPageEvent',
        ),
    ]
